const ActionTypes =  {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_USER: "GET_USER",
  GET_ALL_BOOKS: "GET_ALL_BOOKS",
  GET_BOOK: "GET_BOOK",
  LOG_OUT:"LOG_OUT",
  GET_BORROWED_BOOKS:"GET_BORROWED_BOOKS"
};

export default ActionTypes;
